version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -X main.Version={{.Tag}}
checksum:
  name_template: 'checksums.txt'
