version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -X main.Version={{.Tag}}
checksum:
  name_template: 'checksums.txt'
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"
    formats: [tar.gz]
